.\" Copyright (c) 2019 Tim van der Molen <tim@kariliq.nl>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd June 30, 2023
.Dt SIGBAK 1
.Os
.Sh NAME
.Nm sigbak
.Nd export messages from Signal Android backups
.Sh SYNOPSIS
.Nm sigbak
.Ar command
.Op Ar argument ...
.Sh DESCRIPTION
.Nm
is a utility to read the backups created by the Signal Android app.
It can be used to export messages, attachments and other data.
.Pp
A Signal backup consists primarily of an SQLite database.
This database contains the messages, amongst other things.
Attachments, avatars and stickers, however, are stored as separate files in the
backup.
.Pp
Every Signal backup is encrypted with a 30-digit passphrase.
By default,
.Nm
prompts for the passphrase.
Alternatively, the
.Fl p
option (see below) may be used to specify a file that contains the passphrase.
Whitespace in the passphrase is ignored.
.Pp
The commands are as follows:
.Bl -tag -width Ds
.Tg check
.It Ic check-backup Oo Fl p Ar passfile Oc Ar backup
.D1 Pq Alias: Ic check
.Pp
Check that the file
.Ar backup
can be decrypted and parsed correctly.
The check is aborted after the first encountered error.
.Tg dump
.It Ic dump-backup Oo Fl p Ar passfile Oc Ar backup
.D1 Pq Alias: Ic dump
.Pp
Print the raw contents of the file
.Ar backup
in a readable format on standard output.
.Tg att
.It Xo
.Ic export-attachments
.Op Fl a
.Oo Fl p Ar passfile Oc
.Ar backup Op Ar directory
.Xc
.D1 Pq Alias: Ic att
.Pp
Export the attachments from the file
.Ar backup .
The attachment files are created in separate directories, one for each
conversation.
These directories are created in
.Ar directory ,
or in the current directory if
.Ar directory
is not specified.
.Pp
By default, long-message attachments are not exported.
Long-message attachments contain the text of longer messages.
The
.Fl a
option may be used to export these attachments, too.
.Tg avt
.It Ic export-avatars Oo Fl p Ar passfile Oc Ar backup Op Ar directory
.D1 Pq Alias: Ic avt
.Pp
Export all avatars from the file
.Ar backup
to
.Ar directory ,
or to the current directory if
.Ar directory
is not specified.
.Tg db
.It Ic export-database Oo Fl p Ar passfile Oc Ar backup Ar database
.D1 Pq Alias: Ic db
.Pp
Export the SQLite database from the file
.Ar backup
to the file
.Ar database .
.Tg msg
.It Xo
.Ic export-messages
.Oo Fl f Ar format Oc
.Oo Fl p Ar passfile Oc
.Ar backup Op Ar directory
.Xc
.D1 Pq Alias: Ic msg
.Pp
Export the messages from the file
.Ar backup .
The messages are written to separate files, one for each conversation.
These files are created in
.Ar directory ,
or in the current directory if
.Ar directory
is not specified.
.Pp
The
.Fl f
option may be used to specify the output format.
The following output formats are supported:
.Bl -tag -width Ds
.It Cm csv
Messages are written in CSV (comma-separated values) format.
See the
.Sx CSV FORMAT
section below for details.
.It Cm maildir
Messages are written as emails in maildir format.
In this case, conversations are not written to separate files, but to separate
maildir directories.
.It Cm text
Messages are written as plain text.
This is the default.
.El
.Tg stk
.It Ic export-stickers Oo Fl p Ar passfile Oc Ar backup Op Ar directory
.D1 Pq Alias: Ic stk
.Pp
Export all stickers from the file
.Ar backup
to
.Ar directory ,
or to the current directory if
.Ar directory
is not specified.
.El
.Sh CSV FORMAT
The
.Ic export-messages
command can export messages in CSV format.
In this format, each record describes either a message or a message reaction,
and consists of the following eight fields.
.Pp
The
.Em first
field is an integer specifying the time a message or reaction was sent.
For incoming messages, the
.Em second
field is an integer specifying the time a message or reaction was received.
The times in these two fields are specified in Unix time, with millisecond
precision.
.Pp
The
.Em third
field is an integer specifying the thread id.
.Pp
The
.Em fourth
field is an integer specifying the message type.
A value of 0 indicates an incoming message, 1 indicates an outgoing message,
and 2 indicates a reaction.
Reaction records always immediately follow after the record of the message they
are reactions to.
.Pp
The
.Em fifth
field is an integer specifying the number of attachments a message has.
For reactions, this field is 0.
.Pp
The
.Em sixth
field is a string containing the phone number of the sender or recipient.
For outgoing messages sent to a group, this field is the string
.Sq group .
.Pp
The
.Em seventh
field is a string containing the name of the sender, recipient or group.
.Pp
The
.Em eighth
field is a string containing the message text or reaction emoji.
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
Export all messages from the file
.Pa signal.backup
to the directory
.Pa messages :
.Pp
.Dl $ sigbak export-messages signal.backup messages
.Pp
First create a passphrase file, then export all messages and attachments:
.Bd -literal -offset indent
$ echo 01234 56789 01234 56789 01234 56789 > passfile
$ sigbak export-messages -p passfile signal.backup messages
$ sigbak export-attachments -p passfile signal.backup attachments
.Ed
.Pp
Export the SQLite database and use
.Xr sqlite3 1
to view the contents of the
.Sq sms
table:
.Bd -literal -offset indent
$ sigbak export-database signal.backup signal.db
$ sqlite3 signal.db 'select * from sms' | less
.Ed
.Sh SEE ALSO
.Lk https://github.com/tbvdm/sigbak
.Sh AUTHORS
The
.Nm
utility was written by
.An Tim van der Molen Aq Mt tim@kariliq.nl .
